import { ToastProvider } from "@/components/ui";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import DashboardBg from "@/components/layout/DashboardBg";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <ToastProvider>
              <div className="h-full flex flex-col">
                <DashboardBg/>
                <main className="flex-1">{children}</main>
              </div>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
