export const aboutPageTemplate = {
  id: 'about',
  name: 'About Page Template',
  description:
    'Complete About page template with Hero, Content, Statistics, Vision/Mission, and Team sections',
  thumbnail:
    'https://api.builder.io/api/v1/image/assets/TEMP/95eb0e2f9524f8af6f23bb1c251d150d9a1e9b8c?width=200&h=150&fit=crop',
  parents: [
    // Hero Section
    {
      id: 1,
      size: { height: 300, background: '#000000' },
      rnds: [
        {
          id: 1,
          width: { desktop: 800, laptop: 640, tablet: 480, mobile: 320 },
          height: { desktop: 200, laptop: 160, tablet: 120, mobile: 80 },
          x: { desktop: 150, laptop: 120, tablet: 90, mobile: 60 },
          y: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
          elements: [
            {
              id: 1,
              type: 'text',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
              width: { desktop: 800, laptop: 640, tablet: 480, mobile: 320 },
              height: { desktop: 60, laptop: 48, tablet: 36, mobile: 24 },
              content: 'About Azure Innovations',
              fontSize: { desktop: 48, laptop: 38, tablet: 29, mobile: 19 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              textAlign: 'center',
              fontWeight: '400',
              lineHeight: '60px',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
      ],
    },
    // Main Content Section
    {
      id: 2,
      size: { height: 700, background: '#ffffff' },
      rnds: [
        // Text Content
        {
          id: 2,
          width: { desktop: 664, laptop: 531, tablet: 398, mobile: 266 },
          height: { desktop: 600, laptop: 480, tablet: 360, mobile: 240 },
          x: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
          y: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
          elements: [
            {
              id: 2,
              type: 'paragraph',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 664, laptop: 531, tablet: 398, mobile: 266 },
              height: { desktop: 600, laptop: 480, tablet: 360, mobile: 240 },
              content: `Service Provider for products as well as Apple Corporate partners, having <strong>head office at Naraina (Delhi)</strong> and branch office at Noida, Gurgaon.<br/><br/>We are also <strong>MS Surface Partner</strong>. As an organisation we believe in teamwork, diversity, innovation and integrity. We're driven by professional eminence and always place our customers at the centre of anything and everything we do. Azure Innovations Corporate Background: Azure Innovations, commencing its operations since long. A passionate management team with well experienced Engineers and Professional Business Development team makes Azure Innovations as a best choice for Apple Solutions.<br/><br/>To service, service and service was the commitment we gave to our clients. While this continues to be the bedrock, today we are well established as a Apple Reseller, Service Provider.<br/><br/>This has happened only by virtue of a clear understanding of the future we were seeking and what it takes to achieve that future. So with time and evolving goals came more people, more growth and more importantly an insightful understanding of Apple technology. Our Customer Support services focus on customer satisfaction. The service offerings range from fundamental hardware and software Support to out-tasking services. Based on the combination of flexible support portfolio, pro-active way of working and our focus on the every purchase.`,
              fontSize: { desktop: 15, laptop: 12, tablet: 9, mobile: 6 },
              fontFamily: 'Poppins, sans-serif',
              color: '#000000',
              backgroundColor: 'transparent',
              textAlign: 'justify',
              fontWeight: '300',
              lineHeight: '28px',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
        // Image
        {
          id: 3,
          width: { desktop: 531, laptop: 425, tablet: 319, mobile: 212 },
          height: { desktop: 640, laptop: 512, tablet: 384, mobile: 256 },
          x: { desktop: 800, laptop: 640, tablet: 480, mobile: 320 },
          y: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
          elements: [
            {
              id: 3,
              type: 'image',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 531, laptop: 425, tablet: 319, mobile: 212 },
              height: { desktop: 640, laptop: 512, tablet: 384, mobile: 256 },
              content: '',
              imageUrl:
                'https://api.builder.io/api/v1/image/assets/TEMP/95eb0e2f9524f8af6f23bb1c251d150d9a1e9b8c?width=1062',
              borderRadius: 8,
              border: 'none',
              objectFit: 'cover',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
            },
          ],
        },
      ],
    },
    // Divider
    {
      id: 3,
      size: { height: 50, background: '#ffffff' },
      rnds: [
        {
          id: 4,
          width: { desktop: 1200, laptop: 960, tablet: 720, mobile: 480 },
          height: { desktop: 1, laptop: 1, tablet: 1, mobile: 1 },
          x: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
          y: { desktop: 25, laptop: 20, tablet: 15, mobile: 10 },
          elements: [
            {
              id: 4,
              type: 'div',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 1200, laptop: 960, tablet: 720, mobile: 480 },
              height: { desktop: 1, laptop: 1, tablet: 1, mobile: 1 },
              content: '',
              backgroundColor: '#e5e7eb',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
      ],
    },
    // Statistics Section
    {
      id: 4,
      size: { height: 200, background: '#ffffff' },
      rnds: [
        // 20k Happy Customers
        {
          id: 5,
          width: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
          height: { desktop: 120, laptop: 96, tablet: 72, mobile: 48 },
          x: { desktop: 200, laptop: 160, tablet: 120, mobile: 80 },
          y: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
          elements: [
            {
              id: 5,
              type: 'text',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
              height: { desktop: 56, laptop: 45, tablet: 34, mobile: 22 },
              content: '20k',
              fontSize: { desktop: 48, laptop: 38, tablet: 29, mobile: 19 },
              fontFamily: 'Arial, sans-serif',
              color: '#000000',
              backgroundColor: 'transparent',
              textAlign: 'center',
              fontWeight: '500',
              lineHeight: '56px',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
            {
              id: 6,
              type: 'text',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 72, laptop: 58, tablet: 43, mobile: 29 },
              width: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
              height: { desktop: 28, laptop: 22, tablet: 17, mobile: 11 },
              content: 'Happy Customers',
              fontSize: { desktop: 18, laptop: 14, tablet: 11, mobile: 7 },
              fontFamily: 'Arial, sans-serif',
              color: '#18181b',
              backgroundColor: 'transparent',
              textAlign: 'center',
              fontWeight: '300',
              lineHeight: '28px',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
        // Divider
        {
          id: 6,
          width: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
          height: { desktop: 1, laptop: 1, tablet: 1, mobile: 1 },
          x: { desktop: 550, laptop: 440, tablet: 330, mobile: 220 },
          y: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
          elements: [
            {
              id: 7,
              type: 'div',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
              height: { desktop: 1, laptop: 1, tablet: 1, mobile: 1 },
              content: '',
              background:
                'linear-gradient(to right, #ffffff, #d1d5db, #ffffff)',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
        // 20+ Years Experience
        {
          id: 7,
          width: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
          height: { desktop: 120, laptop: 96, tablet: 72, mobile: 48 },
          x: { desktop: 700, laptop: 560, tablet: 420, mobile: 280 },
          y: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
          elements: [
            {
              id: 8,
              type: 'text',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
              height: { desktop: 56, laptop: 45, tablet: 34, mobile: 22 },
              content: '20+',
              fontSize: { desktop: 48, laptop: 38, tablet: 29, mobile: 19 },
              fontFamily: 'Arial, sans-serif',
              color: '#000000',
              backgroundColor: 'transparent',
              textAlign: 'center',
              fontWeight: '500',
              lineHeight: '56px',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
            {
              id: 9,
              type: 'text',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 72, laptop: 58, tablet: 43, mobile: 29 },
              width: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
              height: { desktop: 28, laptop: 22, tablet: 17, mobile: 11 },
              content: 'Year of Experience',
              fontSize: { desktop: 18, laptop: 14, tablet: 11, mobile: 7 },
              fontFamily: 'Arial, sans-serif',
              color: '#18181b',
              backgroundColor: 'transparent',
              textAlign: 'center',
              fontWeight: '300',
              lineHeight: '28px',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
        // Divider
        {
          id: 8,
          width: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
          height: { desktop: 1, laptop: 1, tablet: 1, mobile: 1 },
          x: { desktop: 1050, laptop: 840, tablet: 630, mobile: 420 },
          y: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
          elements: [
            {
              id: 10,
              type: 'div',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
              height: { desktop: 1, laptop: 1, tablet: 1, mobile: 1 },
              content: '',
              background:
                'linear-gradient(to right, #ffffff, #d1d5db, #ffffff)',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
        // 100+ Clients Served
        {
          id: 9,
          width: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
          height: { desktop: 120, laptop: 96, tablet: 72, mobile: 48 },
          x: { desktop: 1200, laptop: 960, tablet: 720, mobile: 480 },
          y: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
          elements: [
            {
              id: 11,
              type: 'text',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
              height: { desktop: 56, laptop: 45, tablet: 34, mobile: 22 },
              content: '100+',
              fontSize: { desktop: 48, laptop: 38, tablet: 29, mobile: 19 },
              fontFamily: 'Arial, sans-serif',
              color: '#000000',
              backgroundColor: 'transparent',
              textAlign: 'center',
              fontWeight: '500',
              lineHeight: '56px',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
            {
              id: 12,
              type: 'text',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 72, laptop: 58, tablet: 43, mobile: 29 },
              width: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
              height: { desktop: 28, laptop: 22, tablet: 17, mobile: 11 },
              content: 'Clients Served',
              fontSize: { desktop: 18, laptop: 14, tablet: 11, mobile: 7 },
              fontFamily: 'Arial, sans-serif',
              color: '#18181b',
              backgroundColor: 'transparent',
              textAlign: 'center',
              fontWeight: '300',
              lineHeight: '28px',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
      ],
    },
    // Another Divider
    {
      id: 5,
      size: { height: 120, background: '#ffffff' }, // matches your format
      rnds: [
        {
          id: 10,
          width: { desktop: 1200, laptop: 960, tablet: 720, mobile: 480 },
          height: { desktop: 1, laptop: 1, tablet: 1, mobile: 1 },
          x: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
          y: { desktop: 25, laptop: 20, tablet: 15, mobile: 10 },
          elements: [
            {
              id: 13,
              type: 'div',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 1200, laptop: 960, tablet: 720, mobile: 480 },
              height: { desktop: 1, laptop: 1, tablet: 1, mobile: 1 },
              content: '',
              backgroundColor: '#e5e7eb',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
      ],
    },
    // Vision/Mission Section
    {
      id: 6,
      size: { height: 350, background: '#ffffff' },
      rnds: [
        // Vision Box
        {
          id: 11,
          width: { desktop: 610, laptop: 488, tablet: 366, mobile: 244 },
          height: { desktop: 282, laptop: 226, tablet: 169, mobile: 113 },
          x: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
          y: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
          elements: [
            {
              id: 14,
              type: 'div',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 610, laptop: 488, tablet: 366, mobile: 244 },
              height: { desktop: 282, laptop: 226, tablet: 169, mobile: 113 },
              content: '',
              backgroundColor: '#e5e7eb',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 48, right: 48, bottom: 48, left: 48 },
              borderRadius: 0,
              border: 'none',
            },
            {
              id: 15,
              type: 'text',
              x: { desktop: 48, laptop: 38, tablet: 29, mobile: 19 },
              y: { desktop: 48, laptop: 38, tablet: 29, mobile: 19 },
              width: { desktop: 514, laptop: 411, tablet: 308, mobile: 206 },
              height: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
              content: 'Our Vision',
              fontSize: { desktop: 36, laptop: 29, tablet: 22, mobile: 14 },
              fontFamily: 'Arial, sans-serif',
              color: '#18181b',
              backgroundColor: 'transparent',
              textAlign: 'left',
              fontWeight: '500',
              lineHeight: '50px',
              margin: { top: 0, right: 0, bottom: 20, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
            {
              id: 16,
              type: 'paragraph',
              x: { desktop: 48, laptop: 38, tablet: 29, mobile: 19 },
              y: { desktop: 118, laptop: 94, tablet: 71, mobile: 47 },
              width: { desktop: 500, laptop: 400, tablet: 300, mobile: 200 },
              height: { desktop: 116, laptop: 93, tablet: 70, mobile: 46 },
              content:
                'To be a leading technology partner, delivering innovative Apple and IT solutions that empower our clients to grow, adapt, and succeed in a digital-first world.',
              fontSize: { desktop: 18, laptop: 14, tablet: 11, mobile: 7 },
              fontFamily: 'Arial, sans-serif',
              color: '#18181b',
              backgroundColor: 'transparent',
              textAlign: 'justify',
              fontWeight: '300',
              lineHeight: '28px',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
        // Mission Box
        {
          id: 12,
          width: { desktop: 610, laptop: 488, tablet: 366, mobile: 244 },
          height: { desktop: 282, laptop: 226, tablet: 169, mobile: 113 },
          x: { desktop: 750, laptop: 600, tablet: 450, mobile: 300 },
          y: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
          elements: [
            {
              id: 17,
              type: 'div',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 610, laptop: 488, tablet: 366, mobile: 244 },
              height: { desktop: 282, laptop: 226, tablet: 169, mobile: 113 },
              content: '',
              backgroundColor: '#18181b',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 48, right: 48, bottom: 48, left: 48 },
              borderRadius: 0,
              border: 'none',
            },
            {
              id: 18,
              type: 'text',
              x: { desktop: 48, laptop: 38, tablet: 29, mobile: 19 },
              y: { desktop: 48, laptop: 38, tablet: 29, mobile: 19 },
              width: { desktop: 514, laptop: 411, tablet: 308, mobile: 206 },
              height: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
              content: 'Our Mission',
              fontSize: { desktop: 36, laptop: 29, tablet: 22, mobile: 14 },
              fontFamily: 'Arial, sans-serif',
              color: '#f5f5f5',
              backgroundColor: 'transparent',
              textAlign: 'left',
              fontWeight: '500',
              lineHeight: '50px',
              margin: { top: 0, right: 0, bottom: 20, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
            {
              id: 19,
              type: 'paragraph',
              x: { desktop: 48, laptop: 38, tablet: 29, mobile: 19 },
              y: { desktop: 118, laptop: 94, tablet: 71, mobile: 47 },
              width: { desktop: 500, laptop: 400, tablet: 300, mobile: 200 },
              height: { desktop: 116, laptop: 93, tablet: 70, mobile: 46 },
              content:
                'To provide authentic Apple products, reliable IT solutions, and exceptional customer service through innovation, integrity, and a commitment to continuous improvement.',
              fontSize: { desktop: 18, laptop: 14, tablet: 11, mobile: 7 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              textAlign: 'justify',
              fontWeight: '300',
              lineHeight: '28px',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
      ],
    },
    // Team Section
    {
      id: 7,
      size: { height: 700, background: '#000000' },
      rnds: [
        // Section Title
        {
          id: 13,
          width: { desktop: 1200, laptop: 960, tablet: 720, mobile: 480 },
          height: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
          x: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
          y: { desktop: 48, laptop: 38, tablet: 29, mobile: 19 },
          elements: [
            {
              id: 20,
              type: 'text',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 1200, laptop: 960, tablet: 720, mobile: 480 },
              height: { desktop: 58, laptop: 46, tablet: 35, mobile: 23 },
              content: 'Managing Director & Co-Founder',
              fontSize: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              textAlign: 'left',
              fontWeight: '400',
              lineHeight: '58px',
              margin: { top: 0, right: 0, bottom: 48, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
        // Team Member 1 - Sanjeev Sharma
        {
          id: 14,
          width: { desktop: 360, laptop: 288, tablet: 216, mobile: 144 },
          height: { desktop: 500, laptop: 400, tablet: 300, mobile: 200 },
          x: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
          y: { desktop: 150, laptop: 120, tablet: 90, mobile: 60 },
          elements: [
            {
              id: 21,
              type: 'div',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 360, laptop: 288, tablet: 216, mobile: 144 },
              height: { desktop: 500, laptop: 400, tablet: 300, mobile: 200 },
              content: '',
              backgroundColor: '#101010',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 16,
              border: '1px solid #2F2F2F',
            },
            {
              id: 22,
              type: 'image',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 360, laptop: 288, tablet: 216, mobile: 144 },
              height: { desktop: 360, laptop: 288, tablet: 216, mobile: 144 },
              content: '',
              imageUrl: '/assets/images/cofounder.png',
              borderRadius: 8,
              border: 'none',
              objectFit: 'cover',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
            },
            {
              id: 23,
              type: 'text',
              x: { desktop: 16, laptop: 13, tablet: 10, mobile: 6 },
              y: { desktop: 368, laptop: 294, tablet: 221, mobile: 147 },
              width: { desktop: 328, laptop: 262, tablet: 197, mobile: 131 },
              height: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
              content: 'Sanjeev Sharma',
              fontSize: { desktop: 24, laptop: 19, tablet: 14, mobile: 10 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              textAlign: 'left',
              fontWeight: '400',
              lineHeight: '32px',
              margin: { top: 8, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
            {
              id: 24,
              type: 'text',
              x: { desktop: 16, laptop: 13, tablet: 10, mobile: 6 },
              y: { desktop: 408, laptop: 326, tablet: 245, mobile: 163 },
              width: { desktop: 328, laptop: 262, tablet: 197, mobile: 131 },
              height: { desktop: 24, laptop: 19, tablet: 14, mobile: 10 },
              content: 'Managing director and cofounder',
              fontSize: { desktop: 14, laptop: 11, tablet: 8, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              textAlign: 'left',
              fontWeight: '300',
              lineHeight: '20px',
              margin: { top: 0, right: 0, bottom: 16, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
        // Team Member 2 - Jaj Padmakaran
        {
          id: 15,
          width: { desktop: 360, laptop: 288, tablet: 216, mobile: 144 },
          height: { desktop: 500, laptop: 400, tablet: 300, mobile: 200 },
          x: { desktop: 500, laptop: 400, tablet: 300, mobile: 200 },
          y: { desktop: 150, laptop: 120, tablet: 90, mobile: 60 },
          elements: [
            {
              id: 25,
              type: 'div',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 360, laptop: 288, tablet: 216, mobile: 144 },
              height: { desktop: 500, laptop: 400, tablet: 300, mobile: 200 },
              content: '',
              backgroundColor: '#101010',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 16,
              border: '1px solid #2F2F2F',
            },
            {
              id: 26,
              type: 'image',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 360, laptop: 288, tablet: 216, mobile: 144 },
              height: { desktop: 360, laptop: 288, tablet: 216, mobile: 144 },
              content: '',
              imageUrl: '/assets/images/cofounder2.png',
              borderRadius: 8,
              border: 'none',
              objectFit: 'cover',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
            },
            {
              id: 27,
              type: 'text',
              x: { desktop: 16, laptop: 13, tablet: 10, mobile: 6 },
              y: { desktop: 368, laptop: 294, tablet: 221, mobile: 147 },
              width: { desktop: 328, laptop: 262, tablet: 197, mobile: 131 },
              height: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
              content: 'Jaj Padmakaran',
              fontSize: { desktop: 24, laptop: 19, tablet: 14, mobile: 10 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              textAlign: 'left',
              fontWeight: '400',
              lineHeight: '32px',
              margin: { top: 8, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
            {
              id: 28,
              type: 'text',
              x: { desktop: 16, laptop: 13, tablet: 10, mobile: 6 },
              y: { desktop: 408, laptop: 326, tablet: 245, mobile: 163 },
              width: { desktop: 328, laptop: 262, tablet: 197, mobile: 131 },
              height: { desktop: 24, laptop: 19, tablet: 14, mobile: 10 },
              content: 'Technical and Support Services Director',
              fontSize: { desktop: 14, laptop: 11, tablet: 8, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              textAlign: 'left',
              fontWeight: '300',
              lineHeight: '20px',
              margin: { top: 0, right: 0, bottom: 16, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
        // Team Member 3 - Parag Kohli
        {
          id: 16,
          width: { desktop: 360, laptop: 288, tablet: 216, mobile: 144 },
          height: { desktop: 500, laptop: 400, tablet: 300, mobile: 200 },
          x: { desktop: 900, laptop: 720, tablet: 540, mobile: 360 },
          y: { desktop: 150, laptop: 120, tablet: 90, mobile: 60 },
          elements: [
            {
              id: 29,
              type: 'div',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 360, laptop: 288, tablet: 216, mobile: 144 },
              height: { desktop: 500, laptop: 400, tablet: 300, mobile: 200 },
              content: '',
              backgroundColor: '#101010',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 16,
              border: '1px solid #2F2F2F',
            },
            {
              id: 30,
              type: 'image',
              x: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              y: { desktop: 0, laptop: 0, tablet: 0, mobile: 0 },
              width: { desktop: 360, laptop: 288, tablet: 216, mobile: 144 },
              height: { desktop: 360, laptop: 288, tablet: 216, mobile: 144 },
              content: '',
              imageUrl: '/assets/images/cofounder3.png',
              borderRadius: 8,
              border: 'none',
              objectFit: 'cover',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
            },
            {
              id: 31,
              type: 'text',
              x: { desktop: 16, laptop: 13, tablet: 10, mobile: 6 },
              y: { desktop: 368, laptop: 294, tablet: 221, mobile: 147 },
              width: { desktop: 328, laptop: 262, tablet: 197, mobile: 131 },
              height: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
              content: 'Parag Kohli',
              fontSize: { desktop: 24, laptop: 19, tablet: 14, mobile: 10 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              textAlign: 'left',
              fontWeight: '400',
              lineHeight: '32px',
              margin: { top: 8, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
            {
              id: 32,
              type: 'text',
              x: { desktop: 16, laptop: 13, tablet: 10, mobile: 6 },
              y: { desktop: 408, laptop: 326, tablet: 245, mobile: 163 },
              width: { desktop: 328, laptop: 262, tablet: 197, mobile: 131 },
              height: { desktop: 24, laptop: 19, tablet: 14, mobile: 10 },
              content: 'Pre Sales Head',
              fontSize: { desktop: 14, laptop: 11, tablet: 8, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              textAlign: 'left',
              fontWeight: '300',
              lineHeight: '20px',
              margin: { top: 0, right: 0, bottom: 16, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
      ],
    },
  ],
};
