// templates/contact.js
export const contactPageTemplate = {
  id: 'contact',
  name: 'Contact Us',
  description:
    'Professional contact page with form, location, and contact information',
  thumbnail:
    'https://images.unsplash.com/photo-1423666639041-f56000c27a9a?w=200&h=150&fit=crop',
  parents: [
    // Header Section
    {
      size: {
        height: 400,
        background: 'linear-gradient(135deg, #00b894 0%, #00a085 100%)',
      },
      rnds: [
        {
          width: { desktop: 500, laptop: 400, tablet: 300, mobile: 200 },
          height: { desktop: 150, laptop: 120, tablet: 90, mobile: 60 },
          x: { desktop: 150, laptop: 120, tablet: 90, mobile: 60 },
          y: { desktop: 125, laptop: 100, tablet: 75, mobile: 50 },
          elements: [
            {
              type: 'text',
              x: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              y: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              width: { desktop: 460, laptop: 368, tablet: 276, mobile: 184 },
              height: { desktop: 60, laptop: 48, tablet: 36, mobile: 24 },
              content: 'Get In Touch',
              fontSize: { desktop: 38, laptop: 30, tablet: 23, mobile: 15 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 10, right: 20, bottom: 10, left: 20 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'text',
              x: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              y: { desktop: 90, laptop: 72, tablet: 54, mobile: 36 },
              width: { desktop: 460, laptop: 368, tablet: 276, mobile: 184 },
              height: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
              content: "We'd love to hear from you. Send us a message!",
              fontSize: { desktop: 18, laptop: 14, tablet: 11, mobile: 7 },
              fontFamily: 'Arial, sans-serif',
              color: '#e8fff8',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 20, bottom: 5, left: 20 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
      ],
    },
    // Contact Form & Info Section
    {
      size: { height: 600, background: '#ffffff' },
      rnds: [
        // Contact Form
        {
          width: { desktop: 400, laptop: 320, tablet: 240, mobile: 160 },
          height: { desktop: 450, laptop: 360, tablet: 270, mobile: 180 },
          x: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
          y: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
          elements: [
            {
              type: 'text',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              width: { desktop: 380, laptop: 304, tablet: 228, mobile: 152 },
              height: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
              content: 'Send us a Message',
              fontSize: { desktop: 24, laptop: 19, tablet: 14, mobile: 10 },
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'paragraph',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 60, laptop: 48, tablet: 36, mobile: 24 },
              width: { desktop: 380, laptop: 304, tablet: 228, mobile: 152 },
              height: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
              content:
                '<div style="padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px; background: #f9f9f9;"><p style="margin-bottom: 15px; font-weight: bold; color: #333;">Contact Form</p><p style="margin-bottom: 10px; padding: 8px; border: 1px solid #ddd; border-radius: 4px; background: white;">📧 Your Email</p><p style="margin-bottom: 10px; padding: 8px; border: 1px solid #ddd; border-radius: 4px; background: white;">👤 Your Name</p><p style="margin-bottom: 10px; padding: 8px; border: 1px solid #ddd; border-radius: 4px; background: white; min-height: 60px;">💬 Your Message</p></div>',
              fontSize: { desktop: 14, laptop: 11, tablet: 8, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'button',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 380, laptop: 304, tablet: 228, mobile: 152 },
              width: { desktop: 150, laptop: 120, tablet: 90, mobile: 60 },
              height: { desktop: 45, laptop: 36, tablet: 27, mobile: 18 },
              content: 'Send Message',
              fontSize: { desktop: 16, laptop: 13, tablet: 10, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: '#00b894',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 10, right: 20, bottom: 10, left: 20 },
              borderRadius: 8,
              border: 'none',
            },
          ],
        },
        // Contact Information
        {
          width: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
          height: { desktop: 450, laptop: 360, tablet: 270, mobile: 180 },
          x: { desktop: 520, laptop: 416, tablet: 312, mobile: 208 },
          y: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
          elements: [
            {
              type: 'text',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              width: { desktop: 280, laptop: 224, tablet: 168, mobile: 112 },
              height: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
              content: 'Contact Information',
              fontSize: { desktop: 24, laptop: 19, tablet: 14, mobile: 10 },
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'text',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 70, laptop: 56, tablet: 42, mobile: 28 },
              width: { desktop: 280, laptop: 224, tablet: 168, mobile: 112 },
              height: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
              content: '📧 hello@yourcompany.com',
              fontSize: { desktop: 16, laptop: 13, tablet: 10, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: '#f8f9fa',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 10, right: 15, bottom: 10, left: 15 },
              borderRadius: 8,
              border: '1px solid #e0e0e0',
            },
            {
              type: 'text',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 130, laptop: 104, tablet: 78, mobile: 52 },
              width: { desktop: 280, laptop: 224, tablet: 168, mobile: 112 },
              height: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
              content: '📞 +1 (555) 123-4567',
              fontSize: { desktop: 16, laptop: 13, tablet: 10, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: '#f8f9fa',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 10, right: 15, bottom: 10, left: 15 },
              borderRadius: 8,
              border: '1px solid #e0e0e0',
            },
            {
              type: 'text',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 190, laptop: 152, tablet: 114, mobile: 76 },
              width: { desktop: 280, laptop: 224, tablet: 168, mobile: 112 },
              height: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
              content: '📍 123 Business St, City, ST 12345',
              fontSize: { desktop: 16, laptop: 13, tablet: 10, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: '#f8f9fa',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 10, right: 15, bottom: 10, left: 15 },
              borderRadius: 8,
              border: '1px solid #e0e0e0',
            },
            {
              type: 'text',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 260, laptop: 208, tablet: 156, mobile: 104 },
              width: { desktop: 280, laptop: 224, tablet: 168, mobile: 112 },
              height: { desktop: 30, laptop: 24, tablet: 18, mobile: 12 },
              content: 'Business Hours',
              fontSize: { desktop: 18, laptop: 14, tablet: 11, mobile: 7 },
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'paragraph',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
              width: { desktop: 280, laptop: 224, tablet: 168, mobile: 112 },
              height: { desktop: 120, laptop: 96, tablet: 72, mobile: 48 },
              content:
                '<p style="margin-bottom: 8px; color: #666;">Monday - Friday: 9:00 AM - 6:00 PM</p><p style="margin-bottom: 8px; color: #666;">Saturday: 10:00 AM - 4:00 PM</p><p style="margin-bottom: 8px; color: #666;">Sunday: Closed</p><br/><p style="color: #00b894; font-weight: bold;">Response time: Within 24 hours</p>',
              fontSize: { desktop: 14, laptop: 11, tablet: 8, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
      ],
    },
    // Map/Location Section
    {
      size: { height: 350, background: '#f8f9fa' },
      rnds: [
        {
          width: { desktop: 700, laptop: 560, tablet: 420, mobile: 280 },
          height: { desktop: 250, laptop: 200, tablet: 150, mobile: 100 },
          x: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
          y: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
          elements: [
            {
              type: 'text',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              width: { desktop: 680, laptop: 544, tablet: 408, mobile: 272 },
              height: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
              content: 'Visit Our Office',
              fontSize: { desktop: 28, laptop: 22, tablet: 17, mobile: 11 },
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'image',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 60, laptop: 48, tablet: 36, mobile: 24 },
              width: { desktop: 680, laptop: 544, tablet: 408, mobile: 272 },
              height: { desktop: 180, laptop: 144, tablet: 108, mobile: 72 },
              content: 'Office Location Map',
              imageUrl:
                'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=400&fit=crop',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 10,
              border: '1px solid #e0e0e0',
            },
          ],
        },
      ],
    },
  ],
};
