// templates/landing.js
export const landingPageTemplate = {
  id: 'landing',
  name: 'Landing Page',
  description:
    'Professional landing page with hero, services, and contact sections',
  thumbnail:
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=200&h=150&fit=crop',
  parents: [
    // Hero Section
    {
      size: {
        height: 600,
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      },
      rnds: [
        {
          width: { desktop: 500, laptop: 400, tablet: 300, mobile: 200 },
          height: { desktop: 250, laptop: 200, tablet: 150, mobile: 100 },
          x: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
          y: { desktop: 150, laptop: 120, tablet: 90, mobile: 60 },
          elements: [
            {
              type: 'text',
              x: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              y: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              width: { desktop: 460, laptop: 368, tablet: 276, mobile: 184 },
              height: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
              content: 'Welcome to Our Amazing Website',
              fontSize: { desktop: 36, laptop: 29, tablet: 22, mobile: 14 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 10, right: 20, bottom: 10, left: 20 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'text',
              x: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              y: { desktop: 110, laptop: 88, tablet: 66, mobile: 44 },
              width: { desktop: 460, laptop: 368, tablet: 276, mobile: 184 },
              height: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
              content: 'Transform your business with our innovative solutions',
              fontSize: { desktop: 18, laptop: 14, tablet: 11, mobile: 7 },
              fontFamily: 'Arial, sans-serif',
              color: '#e8e8e8',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 20, bottom: 5, left: 20 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'button',
              x: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              y: { desktop: 170, laptop: 136, tablet: 102, mobile: 68 },
              width: { desktop: 160, laptop: 128, tablet: 96, mobile: 64 },
              height: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
              content: 'Get Started Today',
              fontSize: { desktop: 16, laptop: 13, tablet: 10, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: '#ff6b6b',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 12, right: 24, bottom: 12, left: 24 },
              borderRadius: 25,
              border: 'none',
            },
            {
              type: 'button',
              x: { desktop: 200, laptop: 160, tablet: 120, mobile: 80 },
              y: { desktop: 170, laptop: 136, tablet: 102, mobile: 68 },
              width: { desktop: 140, laptop: 112, tablet: 84, mobile: 56 },
              height: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
              content: 'Learn More',
              fontSize: { desktop: 16, laptop: 13, tablet: 10, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 12, right: 24, bottom: 12, left: 24 },
              borderRadius: 25,
              border: '2px solid #ffffff',
            },
          ],
        },
      ],
    },
    // Services Section
    {
      size: { height: 500, background: '#f8f9fa' },
      rnds: [
        {
          width: { desktop: 400, laptop: 320, tablet: 240, mobile: 160 },
          height: { desktop: 200, laptop: 160, tablet: 120, mobile: 80 },
          x: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
          y: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
          elements: [
            {
              type: 'text',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              width: { desktop: 380, laptop: 304, tablet: 228, mobile: 152 },
              height: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
              content: 'Our Services',
              fontSize: { desktop: 32, laptop: 26, tablet: 20, mobile: 13 },
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'paragraph',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 70, laptop: 56, tablet: 42, mobile: 28 },
              width: { desktop: 380, laptop: 304, tablet: 228, mobile: 152 },
              height: { desktop: 120, laptop: 96, tablet: 72, mobile: 48 },
              content:
                '<p style="line-height: 1.6;">We provide exceptional services tailored to your specific needs. Our team delivers quality results that drive your business forward.</p>',
              fontSize: { desktop: 16, laptop: 13, tablet: 10, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
        {
          width: { desktop: 250, laptop: 200, tablet: 150, mobile: 100 },
          height: { desktop: 250, laptop: 200, tablet: 150, mobile: 100 },
          x: { desktop: 500, laptop: 400, tablet: 300, mobile: 200 },
          y: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
          elements: [
            {
              type: 'image',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              content: 'Service Image',
              imageUrl:
                'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=400&fit=crop',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 15,
              border: 'none',
            },
          ],
        },
      ],
    },
    // Contact Section
    {
      size: {
        height: 400,
        background: 'linear-gradient(45deg, #f093fb 0%, #f5576c 100%)',
      },
      rnds: [
        {
          width: { desktop: 500, laptop: 400, tablet: 300, mobile: 200 },
          height: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
          x: { desktop: 150, laptop: 120, tablet: 90, mobile: 60 },
          y: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
          elements: [
            {
              type: 'text',
              x: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              y: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              width: { desktop: 460, laptop: 368, tablet: 276, mobile: 184 },
              height: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
              content: 'Get In Touch',
              fontSize: { desktop: 32, laptop: 26, tablet: 20, mobile: 13 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 10, right: 20, bottom: 10, left: 20 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'text',
              x: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              y: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
              width: { desktop: 460, laptop: 368, tablet: 276, mobile: 184 },
              height: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
              content: 'Ready to start your project? Contact us today!',
              fontSize: { desktop: 18, laptop: 14, tablet: 11, mobile: 7 },
              fontFamily: 'Arial, sans-serif',
              color: '#f0f0f0',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 20, bottom: 5, left: 20 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'button',
              x: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              y: { desktop: 140, laptop: 112, tablet: 84, mobile: 56 },
              width: { desktop: 140, laptop: 112, tablet: 84, mobile: 56 },
              height: { desktop: 45, laptop: 36, tablet: 27, mobile: 18 },
              content: 'Contact Us',
              fontSize: { desktop: 16, laptop: 13, tablet: 10, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: '#ffffff',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 10, right: 20, bottom: 10, left: 20 },
              borderRadius: 25,
              border: 'none',
            },
          ],
        },
      ],
    },
  ],
};
