// templates/services.js
export const servicesPageTemplate = {
  id: 'services',
  name: 'Our Services',
  description:
    'Professional services page showcasing different service offerings',
  thumbnail:
    'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=200&h=150&fit=crop',
  parents: [
    // Hero Section
    {
      size: {
        height: 450,
        background: 'linear-gradient(135deg, #6c5ce7 0%, #a29bfe 100%)',
      },
      rnds: [
        {
          width: { desktop: 600, laptop: 480, tablet: 360, mobile: 240 },
          height: { desktop: 180, laptop: 144, tablet: 108, mobile: 72 },
          x: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
          y: { desktop: 135, laptop: 108, tablet: 81, mobile: 54 },
          elements: [
            {
              type: 'text',
              x: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              y: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              width: { desktop: 560, laptop: 448, tablet: 336, mobile: 224 },
              height: { desktop: 70, laptop: 56, tablet: 42, mobile: 28 },
              content: 'Our Services',
              fontSize: { desktop: 42, laptop: 34, tablet: 25, mobile: 17 },
              fontFamily: 'Arial, sans-serif',
              color: '#ffffff',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 10, right: 20, bottom: 10, left: 20 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'text',
              x: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              y: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
              width: { desktop: 560, laptop: 448, tablet: 336, mobile: 224 },
              height: { desktop: 40, laptop: 32, tablet: 24, mobile: 16 },
              content:
                'Comprehensive solutions tailored to your business needs',
              fontSize: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              fontFamily: 'Arial, sans-serif',
              color: '#e8e6ff',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 20, bottom: 5, left: 20 },
              borderRadius: 0,
              border: 'none',
            },
          ],
        },
      ],
    },
    // Services Grid Section
    {
      size: { height: 600, background: '#ffffff' },
      rnds: [
        // Service 1 - Web Development
        {
          width: { desktop: 250, laptop: 200, tablet: 150, mobile: 100 },
          height: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
          x: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
          y: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
          elements: [
            {
              type: 'image',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 120, laptop: 96, tablet: 72, mobile: 48 },
              content: 'Web Development',
              imageUrl:
                'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=200&fit=crop',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 8,
              border: 'none',
            },
            {
              type: 'text',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 140, laptop: 112, tablet: 84, mobile: 56 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 30, laptop: 24, tablet: 18, mobile: 12 },
              content: 'Web Development',
              fontSize: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'paragraph',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 180, laptop: 144, tablet: 108, mobile: 72 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
              content:
                '<p style="line-height: 1.6;">Custom web applications built with modern technologies. Responsive, fast, and user-friendly solutions.</p>',
              fontSize: { desktop: 14, laptop: 11, tablet: 8, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'button',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 270, laptop: 216, tablet: 162, mobile: 108 },
              width: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
              height: { desktop: 25, laptop: 20, tablet: 15, mobile: 10 },
              content: 'Learn More',
              fontSize: { desktop: 12, laptop: 10, tablet: 7, mobile: 5 },
              fontFamily: 'Arial, sans-serif',
              color: '#6c5ce7',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 4,
              border: '1px solid #6c5ce7',
            },
          ],
        },
        // Service 2 - Mobile Apps
        {
          width: { desktop: 250, laptop: 200, tablet: 150, mobile: 100 },
          height: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
          x: { desktop: 320, laptop: 256, tablet: 192, mobile: 128 },
          y: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
          elements: [
            {
              type: 'image',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 120, laptop: 96, tablet: 72, mobile: 48 },
              content: 'Mobile App Development',
              imageUrl:
                'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=400&h=200&fit=crop',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 8,
              border: 'none',
            },
            {
              type: 'text',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 140, laptop: 112, tablet: 84, mobile: 56 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 30, laptop: 24, tablet: 18, mobile: 12 },
              content: 'Mobile App Development',
              fontSize: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'paragraph',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 180, laptop: 144, tablet: 108, mobile: 72 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
              content:
                '<p style="line-height: 1.6;">Native and cross-platform mobile applications for iOS and Android with seamless user experience.</p>',
              fontSize: { desktop: 14, laptop: 11, tablet: 8, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'button',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 270, laptop: 216, tablet: 162, mobile: 108 },
              width: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
              height: { desktop: 25, laptop: 20, tablet: 15, mobile: 10 },
              content: 'Learn More',
              fontSize: { desktop: 12, laptop: 10, tablet: 7, mobile: 5 },
              fontFamily: 'Arial, sans-serif',
              color: '#6c5ce7',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 4,
              border: '1px solid #6c5ce7',
            },
          ],
        },
        // Service 3 - UI/UX Design
        {
          width: { desktop: 250, laptop: 200, tablet: 150, mobile: 100 },
          height: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
          x: { desktop: 590, laptop: 472, tablet: 354, mobile: 236 },
          y: { desktop: 50, laptop: 40, tablet: 30, mobile: 20 },
          elements: [
            {
              type: 'image',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 120, laptop: 96, tablet: 72, mobile: 48 },
              content: 'UI/UX Design',
              imageUrl:
                'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=200&fit=crop',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 8,
              border: 'none',
            },
            {
              type: 'text',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 140, laptop: 112, tablet: 84, mobile: 56 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 30, laptop: 24, tablet: 18, mobile: 12 },
              content: 'UI/UX Design',
              fontSize: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'paragraph',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 180, laptop: 144, tablet: 108, mobile: 72 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
              content:
                '<p style="line-height: 1.6;">Beautiful, intuitive user interfaces and experiences that delight users and drive engagement.</p>',
              fontSize: { desktop: 14, laptop: 11, tablet: 8, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'button',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 270, laptop: 216, tablet: 162, mobile: 108 },
              width: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
              height: { desktop: 25, laptop: 20, tablet: 15, mobile: 10 },
              content: 'Learn More',
              fontSize: { desktop: 12, laptop: 10, tablet: 7, mobile: 5 },
              fontFamily: 'Arial, sans-serif',
              color: '#6c5ce7',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 4,
              border: '1px solid #6c5ce7',
            },
          ],
        },
        // Service 4 - Digital Marketing
        {
          width: { desktop: 250, laptop: 200, tablet: 150, mobile: 100 },
          height: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
          x: { desktop: 185, laptop: 148, tablet: 111, mobile: 74 },
          y: { desktop: 370, laptop: 296, tablet: 222, mobile: 148 },
          elements: [
            {
              type: 'image',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 120, laptop: 96, tablet: 72, mobile: 48 },
              content: 'Digital Marketing',
              imageUrl:
                'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=200&fit=crop',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 8,
              border: 'none',
            },
            {
              type: 'text',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 140, laptop: 112, tablet: 84, mobile: 56 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 30, laptop: 24, tablet: 18, mobile: 12 },
              content: 'Digital Marketing',
              fontSize: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'paragraph',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 180, laptop: 144, tablet: 108, mobile: 72 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
              content:
                '<p style="line-height: 1.6;">Strategic digital marketing campaigns to boost your online presence and drive business growth.</p>',
              fontSize: { desktop: 14, laptop: 11, tablet: 8, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'button',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 270, laptop: 216, tablet: 162, mobile: 108 },
              width: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
              height: { desktop: 25, laptop: 20, tablet: 15, mobile: 10 },
              content: 'Learn More',
              fontSize: { desktop: 12, laptop: 10, tablet: 7, mobile: 5 },
              fontFamily: 'Arial, sans-serif',
              color: '#6c5ce7',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 4,
              border: '1px solid #6c5ce7',
            },
          ],
        },
        // Service 5 - Consulting
        {
          width: { desktop: 250, laptop: 200, tablet: 150, mobile: 100 },
          height: { desktop: 300, laptop: 240, tablet: 180, mobile: 120 },
          x: { desktop: 455, laptop: 364, tablet: 273, mobile: 182 },
          y: { desktop: 370, laptop: 296, tablet: 222, mobile: 148 },
          elements: [
            {
              type: 'image',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 120, laptop: 96, tablet: 72, mobile: 48 },
              content: 'Business Consulting',
              imageUrl:
                'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=200&fit=crop',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              borderRadius: 8,
              border: 'none',
            },
            {
              type: 'text',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 140, laptop: 112, tablet: 84, mobile: 56 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 30, laptop: 24, tablet: 18, mobile: 12 },
              content: 'Business Consulting',
              fontSize: { desktop: 20, laptop: 16, tablet: 12, mobile: 8 },
              fontFamily: 'Arial, sans-serif',
              color: '#333333',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'paragraph',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 180, laptop: 144, tablet: 108, mobile: 72 },
              width: { desktop: 230, laptop: 184, tablet: 138, mobile: 92 },
              height: { desktop: 80, laptop: 64, tablet: 48, mobile: 32 },
              content:
                '<p style="line-height: 1.6;">Expert business consulting to help optimize your operations and achieve your strategic goals.</p>',
              fontSize: { desktop: 14, laptop: 11, tablet: 8, mobile: 6 },
              fontFamily: 'Arial, sans-serif',
              color: '#666666',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 0,
              border: 'none',
            },
            {
              type: 'button',
              x: { desktop: 10, laptop: 8, tablet: 6, mobile: 4 },
              y: { desktop: 270, laptop: 216, tablet: 162, mobile: 108 },
              width: { desktop: 100, laptop: 80, tablet: 60, mobile: 40 },
              height: { desktop: 25, laptop: 20, tablet: 15, mobile: 10 },
              content: 'Learn More',
              fontSize: { desktop: 12, laptop: 10, tablet: 7, mobile: 5 },
              fontFamily: 'Arial, sans-serif',
              color: '#6c5ce7',
              backgroundColor: 'transparent',
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              padding: { top: 5, right: 10, bottom: 5, left: 10 },
              borderRadius: 4,
              border: '1px solid #6c5ce7',
            },
          ],
        },
      ],
    },
  ],
};
